name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/core
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install node dependencies
        run: yarn install

      - name: Test
        run: yarn test --collectCoverage

      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash) -F core
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
